"""Authoritative product metadata, also consumed by the Windows build."""
APP_NAME = "Seekdex"
DISPLAY_NAME = "Seekdex · 索星仪"
APP_ID = "seekdex"
VERSION = "0.5.0-rc2"
PACKAGE_VERSION = "0.5.0rc2"
WINDOWS_VERSION = (0, 5, 0, 2)
RELEASE_STATUS = "Unsigned Release Candidate"
AUTHOR = "ciqing wesley"
HOMEPAGE = "https://github.com/ciqingwesley-create/Seekdex"
LICENSE = "GPL-3.0-only"
DESCRIPTION = "Seekdex · 索星仪是一款开源、本地优先的智能文件与图片搜索工具。"
COPYRIGHT = "Copyright (c) 2026 ciqing wesley"
